import Head from "next/head";
import Navbar from "../components/Navbar";

const MainContainer = ({ children, keywords }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content={"igorchugurov" + keywords} />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div>{children}</div>
    </>
  );
};

export default MainContainer;
